print("Операции + и *")
a = int(input("input number: "))
print(int(a), float(a), bool(a), str(a))
b = int(input("input number: "))
print(int(a) + int(b), int(a) + float(b), int(a) + bool(b))
print(float(a) + int(b), float(a) + float(b), float(a) + bool(b))
print(bool(a) + int(b), bool(a) + float(b), bool(a) + bool(b))
print(str(a) + str(b))
print(int(a) * int(b), int(a) * float(b), int(a) * bool(b), int(a) * str(b))
print(float(a) * int(b), float(a) * float(b), float(a) * bool(b))
print(bool(a) * int(b), bool(a) * float(b), bool(a) * bool(b), bool(a) * str(b))
print(str(a) * int(b), str(a) * bool(b))
